"""add 2fa, lockout, session_version to user

Revision ID: 16e81102842d
Revises: 55711f10b2ce
Create Date: 2026-07-02 12:44:19.177135
"""
from alembic import op
import sqlalchemy as sa


revision = '16e81102842d'
down_revision = '55711f10b2ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default on the NOT NULL columns so this migration is safe on a
    # table that already has rows (backfills existing users with 0/false).
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('recovery_codes_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('session_version', sa.Integer(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_version')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_count')
        batch_op.drop_column('recovery_codes_json')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret_encrypted')

    # ### end Alembic commands ###
