"""add usage_record.alert_sent

Revision ID: 7dd9df5ce610
Revises: 49f892bcf390
Create Date: 2026-07-02 13:14:41.545998
"""
from alembic import op
import sqlalchemy as sa


revision = '7dd9df5ce610'
down_revision = '49f892bcf390'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_sent', sa.Integer(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_record', schema=None) as batch_op:
        batch_op.drop_column('alert_sent')

    # ### end Alembic commands ###
