"""add api_usage_record table

Revision ID: 96740be97484
Revises: c4f2a9b1d7e3
Create Date: 2026-07-08 15:34:10.128199
"""
from alembic import op
import sqlalchemy as sa


revision = '96740be97484'
down_revision = 'c4f2a9b1d7e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('pairs', sa.Integer(), nullable=False),
    sa.Column('last_call_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', name='uq_api_usage_user_period')
    )
    with op.batch_alter_table('api_usage_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_record_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_record_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_record_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_usage_record_period'))

    op.drop_table('api_usage_record')
    # ### end Alembic commands ###
