"""add api_subscription table

Revision ID: e3877a92ffe3
Revises: 96740be97484
Create Date: 2026-07-08 16:03:29.729917
"""
from alembic import op
import sqlalchemy as sa


revision = 'e3877a92ffe3'
down_revision = '96740be97484'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_plan_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_subscription_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_subscription_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_subscription_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_subscription_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_subscription_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_api_subscription_stripe_customer_id'))

    op.drop_table('api_subscription')
    # ### end Alembic commands ###
