import type { AnalysisResult, SimilarityItem } from "@/types/api";
import { sanitizeHtml } from "@/lib/sanitize";

/**
 * Client-side PDF / report export.
 *
 * The project intentionally ships no heavyweight PDF library in the bundle, so
 * we build a self-contained, print-styled HTML document (inline CSS + inline
 * SVG charts — no external assets) and open it in a new window; the user prints
 * it or chooses "Save as PDF". All user/AI-derived text is HTML-escaped, and the
 * one rich-HTML field (analysis_html) is run through the same DOMPurify
 * sanitizer used everywhere else.
 */

export interface PdfSections {
  cover: boolean;
  executiveSummary: boolean;
  similarityMetrics: boolean;
  cloneDetection: boolean;
  aiStructuredReport: boolean;
  aiAnalysisText: boolean;
  codeQuality: boolean;
  sourceCode: boolean;
}

export const DEFAULT_SECTIONS: PdfSections = {
  cover: true,
  executiveSummary: true,
  similarityMetrics: true,
  cloneDetection: true,
  aiStructuredReport: true,
  aiAnalysisText: true,
  codeQuality: true,
  sourceCode: false,
};

type Lang = "en" | "ar";

const LABELS: Record<Lang, Record<string, string>> = {
  en: {
    title: "Code Similarity Analysis Report",
    subtitle: "Structural · Semantic · AI-assisted comparison",
    generated: "Generated",
    analysisId: "Analysis ID",
    language: "Language",
    sources: "Sources",
    combined: "Combined Similarity",
    overall: "Overall Assessment",
    execSummary: "Executive Summary",
    verdict: "Verdict",
    risk: "Risk level",
    kpiClones: "Clone families",
    kpiFindings: "Findings",
    kpiStrongest: "Strongest signal",
    kpiStrength: "Similarity strength",
    similarityMetrics: "Similarity Analysis",
    dimensionBreakdown: "Dimension breakdown",
    radar: "Similarity radar",
    interpretation: "Interpretation",
    metric: "Metric",
    value: "Value",
    structuralMetrics: "Structural & Maintainability Metrics",
    sourceA: "Source A",
    sourceB: "Source B",
    delta: "Δ",
    cloneDetection: "Clone Detection",
    type: "Clone type",
    detected: "Detected",
    notDetected: "Not detected",
    coverage: "Detection coverage",
    activated: "clone families activated",
    yes: "Yes",
    no: "No",
    findings: "AI Findings & Recommendations",
    noFindings: "No specific findings were raised for this comparison.",
    refactoring: "Refactoring suggestion",
    aiAnalysis: "AI Analysis Narrative",
    codeQuality: "Code Quality Review",
    source: "Source Code",
    print: "Print / Save as PDF",
    noData: "No data available for this section.",
    strengthVeryHigh: "Very high",
    strengthHigh: "High",
    strengthModerate: "Moderate",
    strengthLow: "Low",
    riskCritical: "Critical",
    riskHigh: "High",
    riskModerate: "Moderate",
    riskLow: "Low",
    riskNone: "Minimal",
    interpHigh:
      "The two sources are strongly aligned across multiple dimensions, which is a strong indicator of direct or lightly-modified reuse.",
    interpModerate:
      "The sources share a meaningful amount of structure or logic; review the strongest signals below to judge whether the overlap is incidental or deliberate.",
    interpLow:
      "Overall similarity is low. Any matches are likely incidental rather than evidence of shared origin.",
    footer: "Generated by CodeClone",
    mLoc: "Lines of code",
    mSloc: "Source lines (SLOC)",
    mComments: "Comment lines",
    mBlank: "Blank lines",
    mFunctions: "Functions",
    mClasses: "Classes",
    mAvgLine: "Avg. line length",
    mCyclomatic: "Cyclomatic complexity",
    mMaintainability: "Maintainability index",
    mHVolume: "Halstead volume",
    mHDifficulty: "Halstead difficulty",
    mHEffort: "Halstead effort",
  },
  ar: {
    title: "تقرير تحليل تشابه الشيفرة",
    subtitle: "مقارنة بنيوية · دلالية · بمساعدة الذكاء الاصطناعي",
    generated: "أُنشئ في",
    analysisId: "معرّف التحليل",
    language: "اللغة",
    sources: "المصدران",
    combined: "التشابه الكلي",
    overall: "التقييم العام",
    execSummary: "الملخّص التنفيذي",
    verdict: "الحكم",
    risk: "مستوى الخطورة",
    kpiClones: "عائلات النسخ",
    kpiFindings: "الملاحظات",
    kpiStrongest: "أقوى إشارة",
    kpiStrength: "قوة التشابه",
    similarityMetrics: "تحليل التشابه",
    dimensionBreakdown: "تفصيل الأبعاد",
    radar: "رادار التشابه",
    interpretation: "التفسير",
    metric: "المؤشر",
    value: "القيمة",
    structuralMetrics: "المؤشرات البنيوية وقابلية الصيانة",
    sourceA: "المصدر أ",
    sourceB: "المصدر ب",
    delta: "الفرق",
    cloneDetection: "كشف النسخ",
    type: "نوع النسخة",
    detected: "مكتشَف",
    notDetected: "غير مكتشَف",
    coverage: "تغطية الكشف",
    activated: "عائلة نسخ مُفعّلة",
    yes: "نعم",
    no: "لا",
    findings: "ملاحظات وتوصيات الذكاء الاصطناعي",
    noFindings: "لم تُرصد ملاحظات محدّدة لهذه المقارنة.",
    refactoring: "اقتراح إعادة الهيكلة",
    aiAnalysis: "سرد تحليل الذكاء الاصطناعي",
    codeQuality: "مراجعة جودة الشيفرة",
    source: "الشيفرة المصدرية",
    print: "طباعة / حفظ PDF",
    noData: "لا تتوفّر بيانات لهذا القسم.",
    strengthVeryHigh: "مرتفع جدًا",
    strengthHigh: "مرتفع",
    strengthModerate: "متوسط",
    strengthLow: "منخفض",
    riskCritical: "حرِج",
    riskHigh: "مرتفع",
    riskModerate: "متوسط",
    riskLow: "منخفض",
    riskNone: "ضئيل",
    interpHigh:
      "يتوافق المصدران بقوة عبر أبعاد متعددة، وهو مؤشّر قوي على إعادة استخدام مباشرة أو مُعدّلة بشكل طفيف.",
    interpModerate:
      "يتشارك المصدران قدرًا معتبرًا من البنية أو المنطق؛ راجع أقوى الإشارات أدناه لتقدير ما إذا كان التداخل عرضيًا أم مقصودًا.",
    interpLow:
      "التشابه الكلي منخفض. أي تطابقات على الأرجح عرضية لا دليلًا على أصل مشترك.",
    footer: "أُنشئ بواسطة CodeClone",
    mLoc: "عدد الأسطر",
    mSloc: "أسطر المصدر (SLOC)",
    mComments: "أسطر التعليقات",
    mBlank: "الأسطر الفارغة",
    mFunctions: "الدوال",
    mClasses: "الأصناف",
    mAvgLine: "متوسط طول السطر",
    mCyclomatic: "التعقيد الدوري",
    mMaintainability: "مؤشّر قابلية الصيانة",
    mHVolume: "حجم هالستيد",
    mHDifficulty: "صعوبة هالستيد",
    mHEffort: "جهد هالستيد",
  },
};

// Arabic display names for the technical similarity / clone dimensions (English
// left as-is). Falls back to the raw backend name when unmapped.
const AR_SIM_NAMES: Record<string, string> = {
  "Text Similarity": "تشابه النص",
  "Token-Based Similarity": "تشابه التوكنات",
  "Token Similarity (ordered)": "تشابه التوكنات (مرتّب)",
  "Token Similarity (ordered, excluding comments and whitespace)": "تشابه التوكنات (مرتّب، بلا تعليقات ومسافات)",
  "Token Similarity (unordered, with comments and whitespace)": "تشابه التوكنات (غير مرتّب، مع تعليقات ومسافات)",
  "Token Similarity (unordered, excluding comments and whitespace)": "تشابه التوكنات (غير مرتّب، بلا تعليقات ومسافات)",
  "Renamed Clone Similarity": "تشابه النسخ المعاد تسميتها",
  "Graph-Based Similarity": "التشابه البنيوي (الرسم)",
  "Combined Similarity": "التشابه الكلي",
  "AI Similarity": "تشابه الذكاء الاصطناعي",
};
const AR_CLONE_NAMES: Record<string, string> = {
  "Exact Clone": "نسخة مطابقة",
  "Near Miss Clone": "نسخة شبه مطابقة",
  "Parameterized Clone": "نسخة ذات معاملات",
  "Function Clone": "نسخة دالّية",
  "Non-Contiguous Clone": "نسخة غير متّصلة",
  "Structural Clone": "نسخة بنيوية",
  "Reordered Clone": "نسخة معاد ترتيبها",
  "Function Reordered Clone": "نسخة دالّية معاد ترتيبها",
  "Gapped Clone": "نسخة ذات فجوات",
  "Intertwined Clone": "نسخة متشابكة",
  "Semantic Clone": "نسخة دلالية",
};

function esc(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function clamp(n: number, lo = 0, hi = 100): number {
  return Math.max(lo, Math.min(hi, n));
}

function simName(name: string, lang: Lang): string {
  return lang === "ar" ? AR_SIM_NAMES[name] ?? name : name;
}
function cloneName(name: string, lang: Lang): string {
  return lang === "ar" ? AR_CLONE_NAMES[name] ?? name : name;
}

// Concern-oriented colour scale: higher similarity = warmer/hotter.
function strengthColor(v: number): string {
  if (v >= 85) return "#dc2626";
  if (v >= 70) return "#ea580c";
  if (v >= 45) return "#d97706";
  return "#059669";
}
function strengthLabel(v: number, L: Record<string, string>): string {
  if (v >= 85) return L.strengthVeryHigh;
  if (v >= 70) return L.strengthHigh;
  if (v >= 45) return L.strengthModerate;
  return L.strengthLow;
}

const RISK_COLORS: Record<string, string> = {
  critical: "#b91c1c",
  high: "#ea580c",
  moderate: "#d97706",
  low: "#059669",
  none: "#64748b",
};
const SEV_COLORS: Record<string, string> = {
  critical: "#b91c1c",
  high: "#ea580c",
  medium: "#d97706",
  low: "#2563eb",
  info: "#64748b",
};

function riskLabel(level: string, L: Record<string, string>): string {
  const map: Record<string, string> = {
    critical: L.riskCritical,
    high: L.riskHigh,
    moderate: L.riskModerate,
    low: L.riskLow,
    none: L.riskNone,
  };
  return map[level] ?? level;
}

function section(id: string, title: string, inner: string): string {
  return `<section id="sec-${esc(id)}" class="sec"><h2><span class="sec-dot"></span>${esc(title)}</h2>${inner}</section>`;
}

// --- SVG charts (inline, self-contained) --------------------------------

function gaugeSvg(pct: number, label: string): string {
  const v = clamp(pct);
  const r = 56;
  const c = 2 * Math.PI * r;
  const dash = (v / 100) * c;
  const color = strengthColor(v);
  return `<svg viewBox="0 0 150 150" width="150" height="150" role="img" aria-label="${esc(label)} ${v.toFixed(0)}%">
    <circle cx="75" cy="75" r="${r}" fill="none" stroke="rgba(255,255,255,.28)" stroke-width="14"/>
    <circle cx="75" cy="75" r="${r}" fill="none" stroke="${color}" stroke-width="14" stroke-linecap="round"
      stroke-dasharray="${dash.toFixed(1)} ${c.toFixed(1)}" transform="rotate(-90 75 75)"/>
    <text x="75" y="72" text-anchor="middle" font-size="34" font-weight="800" fill="#fff">${v.toFixed(0)}<tspan font-size="18">%</tspan></text>
    <text x="75" y="94" text-anchor="middle" font-size="11" fill="rgba(255,255,255,.85)" letter-spacing=".5">${esc(label)}</text>
  </svg>`;
}

function radarSvg(items: Array<{ name: string; value: number }>, lang: Lang): string {
  const pts = items.filter((i) => Number.isFinite(i.value));
  const n = pts.length;
  if (n < 3) return "";
  const cx = 175;
  const cy = 155;
  const R = 110;
  const angle = (i: number) => -Math.PI / 2 + (i * 2 * Math.PI) / n;
  const coord = (i: number, radius: number) => [cx + radius * Math.cos(angle(i)), cy + radius * Math.sin(angle(i))];

  const rings = [25, 50, 75, 100]
    .map((ring) => {
      const poly = pts
        .map((_, i) => coord(i, (ring / 100) * R).map((x) => x.toFixed(1)).join(","))
        .join(" ");
      return `<polygon points="${poly}" fill="none" stroke="#e2e8f0" stroke-width="1"/>`;
    })
    .join("");
  const axes = pts
    .map((_, i) => {
      const [x, y] = coord(i, R);
      return `<line x1="${cx}" y1="${cy}" x2="${x.toFixed(1)}" y2="${y.toFixed(1)}" stroke="#e2e8f0" stroke-width="1"/>`;
    })
    .join("");
  const valuePoly = pts
    .map((p, i) => coord(i, (clamp(p.value) / 100) * R).map((x) => x.toFixed(1)).join(","))
    .join(" ");
  const dots = pts
    .map((p, i) => {
      const [x, y] = coord(i, (clamp(p.value) / 100) * R);
      return `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="2.6" fill="#4f46e5"/>`;
    })
    .join("");
  const labels = pts
    .map((p, i) => {
      const [x, y] = coord(i, R + 16);
      const anchor = Math.abs(x - cx) < 6 ? "middle" : x > cx ? "start" : "end";
      const short = simName(p.name, lang).replace(/\s*\([^)]*\)/g, "");
      const text = short.length > 22 ? short.slice(0, 21) + "…" : short;
      return `<text x="${x.toFixed(1)}" y="${y.toFixed(1)}" text-anchor="${anchor}" font-size="9.5" fill="#475569" dominant-baseline="middle">${esc(text)}</text>`;
    })
    .join("");
  return `<svg viewBox="0 0 350 320" width="100%" height="auto" style="max-width:360px" role="img" aria-label="${esc(LABELS[lang].radar)}">
    ${rings}${axes}
    <polygon points="${valuePoly}" fill="rgba(79,70,229,.18)" stroke="#4f46e5" stroke-width="2"/>
    ${dots}${labels}
  </svg>`;
}

function barRow(name: string, value: number): string {
  const v = clamp(value);
  const color = strengthColor(v);
  return `<div class="bar-row">
    <div class="bar-head"><span>${esc(name)}</span><span class="bar-val" style="color:${color}">${v.toFixed(1)}%</span></div>
    <div class="bar-track"><div class="bar-fill" style="width:${v.toFixed(1)}%;background:${color}"></div></div>
  </div>`;
}

function kpi(label: string, value: string, accent: string, sub = ""): string {
  return `<div class="kpi">
    <div class="kpi-val" style="color:${accent}">${value}</div>
    <div class="kpi-label">${esc(label)}</div>
    ${sub ? `<div class="kpi-sub">${esc(sub)}</div>` : ""}
  </div>`;
}

function badge(text: string, color: string): string {
  return `<span class="badge" style="--bc:${color}">${esc(text)}</span>`;
}

// --- metric extraction ---------------------------------------------------

function pick(obj: unknown, path: string[]): unknown {
  let cur: unknown = obj;
  for (const key of path) {
    if (cur && typeof cur === "object" && key in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[key];
    } else {
      return undefined;
    }
  }
  return cur;
}
function num(obj: unknown, path: string[]): number | null {
  const v = pick(obj, path);
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}
function fmt(n: number | null, dp: number): string {
  if (n === null) return "—";
  return n.toLocaleString(undefined, { minimumFractionDigits: dp, maximumFractionDigits: dp });
}

function combinedScore(result: AnalysisResult): number {
  const items = Array.isArray(result.similarity_items) ? result.similarity_items : [];
  const combined = items.find((i) => /combined/i.test(i.name));
  if (combined && Number.isFinite(combined.value)) return clamp(Number(combined.value));
  if (result.summary && Number.isFinite(result.summary.similarity)) return clamp(Number(result.summary.similarity));
  if (items.length) return clamp(items.reduce((s, i) => s + Number(i.value || 0), 0) / items.length);
  return 0;
}

function metricsTable(result: AnalysisResult, L: Record<string, string>): string {
  const m1 = result.metrics1;
  const m2 = result.metrics2;
  const rows: Array<{ label: string; p: string[]; dp: number }> = [
    { label: L.mLoc, p: ["universal", "loc"], dp: 0 },
    { label: L.mSloc, p: ["raw", "sloc"], dp: 0 },
    { label: L.mComments, p: ["raw", "comments"], dp: 0 },
    { label: L.mBlank, p: ["universal", "blank"], dp: 0 },
    { label: L.mFunctions, p: ["universal", "function_count"], dp: 0 },
    { label: L.mClasses, p: ["universal", "class_count"], dp: 0 },
    { label: L.mAvgLine, p: ["universal", "avg_line_length"], dp: 1 },
    { label: L.mCyclomatic, p: ["cyclomatic_complexity"], dp: 1 },
    { label: L.mMaintainability, p: ["maintainability_index"], dp: 1 },
    { label: L.mHVolume, p: ["halstead", "volume"], dp: 1 },
    { label: L.mHDifficulty, p: ["halstead", "difficulty"], dp: 1 },
    { label: L.mHEffort, p: ["halstead", "effort"], dp: 0 },
  ];
  const body = rows
    .map((r) => {
      const a = num(m1, r.p);
      const b = num(m2, r.p);
      if (a === null && b === null) return "";
      const delta = a !== null && b !== null ? b - a : null;
      const deltaTxt =
        delta === null || Math.abs(delta) < 1e-9
          ? '<span class="delta-zero">0</span>'
          : `<span class="${delta > 0 ? "delta-up" : "delta-down"}">${delta > 0 ? "▲" : "▼"} ${fmt(Math.abs(delta), r.dp)}</span>`;
      return `<tr><td>${esc(r.label)}</td><td class="numc">${fmt(a, r.dp)}</td><td class="numc">${fmt(b, r.dp)}</td><td class="numc">${deltaTxt}</td></tr>`;
    })
    .filter(Boolean)
    .join("");
  if (!body) return "";
  return `<h3>${esc(L.structuralMetrics)}</h3>
    <table class="mtable"><thead><tr>
      <th>${esc(L.metric)}</th><th class="numc">${esc(L.sourceA)}</th><th class="numc">${esc(L.sourceB)}</th><th class="numc">${esc(L.delta)}</th>
    </tr></thead><tbody>${body}</tbody></table>`;
}

// --- main ----------------------------------------------------------------

export function buildReportHtml(result: AnalysisResult, sections: PdfSections, lang: Lang): string {
  const L = LABELS[lang] ?? LABELS.en;
  const dir = lang === "ar" ? "rtl" : "ltr";
  const locale = lang === "ar" ? "ar" : "en-US";
  const now = new Date().toLocaleString(locale);
  const parts: string[] = [];

  const structured = result.analysis_structured;
  const items = Array.isArray(result.similarity_items) ? result.similarity_items : [];
  const clones = Array.isArray(result.clone_items) ? result.clone_items : [];
  const score = combinedScore(result);
  const risk = structured?.risk_level ?? (score >= 85 ? "high" : score >= 60 ? "moderate" : score >= 35 ? "low" : "none");
  const riskColor = RISK_COLORS[risk] ?? RISK_COLORS.none;
  const detectedClones = clones.filter((c) => c.detected).length;
  const findingCount = structured?.findings?.length ?? 0;
  const nonCombined = items.filter((i) => !/combined/i.test(i.name));
  const strongest = nonCombined.slice().sort((a, b) => Number(b.value) - Number(a.value))[0];
  const labelA = result.source_labels?.code1 || L.sourceA;
  const labelB = result.source_labels?.code2 || L.sourceB;

  // ---- Cover -----------------------------------------------------------
  if (sections.cover) {
    parts.push(`
      <header class="cover">
        <div class="cover-band">
          <div class="cover-head">
            <div class="brand-mark">◇ CodeClone</div>
            <div class="cover-meta-inline">${esc(L.analysisId)}: <b>#${esc(result.saved_analysis_id ?? "—")}</b></div>
          </div>
          <h1>${esc(L.title)}</h1>
          <p class="cover-sub">${esc(L.subtitle)}</p>
          <div class="cover-hero">
            <div class="gauge-wrap">${gaugeSvg(score, L.combined)}</div>
            <div class="cover-facts">
              <div class="fact"><span>${esc(L.sources)}</span><b>${esc(labelA)} <em>↔</em> ${esc(labelB)}</b></div>
              <div class="fact"><span>${esc(L.language)}</span><b>${esc(result.language)}</b></div>
              <div class="fact"><span>${esc(L.risk)}</span><b class="risk-pill">${esc(riskLabel(risk, L))}</b></div>
              <div class="fact"><span>${esc(L.generated)}</span><b>${esc(now)}</b></div>
            </div>
          </div>
        </div>
        ${structured?.verdict ? `<div class="verdict-banner"><span class="v-tag">${esc(L.verdict)}</span> ${esc(structured.verdict)}</div>` : ""}
      </header>`);
  }

  // ---- Executive summary ----------------------------------------------
  if (sections.executiveSummary) {
    const kpis = [
      kpi(L.combined, `${score.toFixed(0)}%`, strengthColor(score), strengthLabel(score, L)),
      kpi(L.risk, riskLabel(risk, L), riskColor),
      kpi(L.kpiClones, `${detectedClones}/${clones.length || 0}`, "#4f46e5"),
      kpi(L.kpiFindings, String(findingCount), findingCount ? "#ea580c" : "#059669"),
      kpi(L.language, esc(result.language), "#0f172a"),
      strongest
        ? kpi(L.kpiStrongest, `${clamp(Number(strongest.value)).toFixed(0)}%`, strengthColor(Number(strongest.value)), simName(strongest.name, lang))
        : "",
    ]
      .filter(Boolean)
      .join("");
    const summaryText = structured?.summary
      ? `<p class="lead">${esc(structured.summary)}</p>`
      : `<p class="lead">${esc(
          score >= 70 ? L.interpHigh : score >= 40 ? L.interpModerate : L.interpLow,
        )}</p>`;
    parts.push(section("exec", L.execSummary, `<div class="kpi-grid">${kpis}</div>${summaryText}`));
  }

  // ---- Similarity analysis (bars + radar + metrics) -------------------
  if (sections.similarityMetrics && (items.length || result.metrics1 || result.metrics2)) {
    const bars = nonCombined.length
      ? `<div class="bars">${nonCombined.map((i: SimilarityItem) => barRow(simName(i.name, lang), Number(i.value))).join("")}</div>`
      : "";
    const radar = radarSvg(
      nonCombined.map((i) => ({ name: i.name, value: Number(i.value) })),
      lang,
    );
    const interp = score >= 70 ? L.interpHigh : score >= 40 ? L.interpModerate : L.interpLow;
    const chartsRow =
      bars || radar
        ? `<div class="charts-row">
            ${bars ? `<div class="charts-bars"><h3>${esc(L.dimensionBreakdown)}</h3>${bars}</div>` : ""}
            ${radar ? `<div class="charts-radar"><h3>${esc(L.radar)}</h3>${radar}</div>` : ""}
          </div>`
        : `<p class="muted">${esc(L.noData)}</p>`;
    parts.push(
      section(
        "sim",
        L.similarityMetrics,
        `${chartsRow}<div class="callout"><b>${esc(L.interpretation)}.</b> ${esc(interp)}</div>${metricsTable(result, L)}`,
      ),
    );
  }

  // ---- Clone detection -------------------------------------------------
  if (sections.cloneDetection && clones.length) {
    const coverage = clones.length ? (detectedClones / clones.length) * 100 : 0;
    const chips = clones
      .map(
        (c) =>
          `<div class="chip ${c.detected ? "on" : "off"}">
            <span class="chip-dot"></span>${esc(cloneName(c.name, lang))}
            <span class="chip-state">${c.detected ? esc(L.detected) : esc(L.notDetected)}</span>
          </div>`,
      )
      .join("");
    parts.push(
      section(
        "clone",
        L.cloneDetection,
        `<div class="coverage">
          <div class="coverage-head"><span>${esc(L.coverage)}</span><b>${detectedClones} / ${clones.length} ${esc(L.activated)}</b></div>
          <div class="bar-track"><div class="bar-fill" style="width:${coverage.toFixed(1)}%;background:#4f46e5"></div></div>
        </div>
        <div class="chips">${chips}</div>`,
      ),
    );
  }

  // ---- AI structured findings -----------------------------------------
  if (sections.aiStructuredReport && structured) {
    const findings = (structured.findings ?? [])
      .map((f) => {
        const c = SEV_COLORS[f.severity] ?? SEV_COLORS.info;
        return `<div class="finding" style="--fc:${c}">
          <div class="finding-head">${badge(f.severity, c)}<b>${esc(f.title)}</b></div>
          <p>${esc(f.description)}</p>
        </div>`;
      })
      .join("");
    const inner =
      `<p><strong>${esc(L.risk)}:</strong> ${badge(riskLabel(structured.risk_level, L), riskColor)}</p>` +
      (findings ? findings : `<p class="muted">${esc(L.noFindings)}</p>`) +
      (structured.refactoring_suggestion
        ? `<div class="callout refactor"><b>${esc(L.refactoring)}.</b> ${esc(structured.refactoring_suggestion)}</div>`
        : "");
    parts.push(section("ai", L.findings, inner));
  }

  // ---- AI narrative ----------------------------------------------------
  if (sections.aiAnalysisText && (result.analysis_html || result.analysis_text)) {
    const inner = result.analysis_html
      ? sanitizeHtml(result.analysis_html)
      : `<pre class="analysis-text">${esc(result.analysis_text)}</pre>`;
    parts.push(section("narr", L.aiAnalysis, `<div class="prose">${inner}</div>`));
  }

  // ---- Code quality ----------------------------------------------------
  if (sections.codeQuality && result.code_smell && (result.code_smell.code1_analysis || result.code_smell.code2_analysis)) {
    parts.push(
      section(
        "quality",
        L.codeQuality,
        `<div class="quality-grid">
          <div class="quality-card"><h3>${esc(labelA)}</h3><pre>${esc(result.code_smell.code1_analysis)}</pre></div>
          <div class="quality-card"><h3>${esc(labelB)}</h3><pre>${esc(result.code_smell.code2_analysis)}</pre></div>
        </div>`,
      ),
    );
  }

  // ---- Source code -----------------------------------------------------
  if (sections.sourceCode) {
    parts.push(
      section(
        "src",
        L.source,
        `<h3>${esc(labelA)}</h3><pre class="code">${esc(result.code1)}</pre>` +
          `<h3>${esc(labelB)}</h3><pre class="code">${esc(result.code2)}</pre>`,
      ),
    );
  }

  const doc = `<!doctype html><html lang="${lang}" dir="${dir}"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${esc(L.title)}</title>
<style>
  :root { --brand:#4f46e5; --brand2:#7c3aed; --ink:#0f172a; --muted:#64748b; --line:#e2e8f0; --soft:#f8fafc; }
  * { box-sizing: border-box; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  html { -webkit-text-size-adjust: 100%; }
  body { font-family: -apple-system, "Segoe UI", Roboto, "Noto Sans Arabic", "Noto Naskh Arabic", sans-serif;
    color: var(--ink); margin: 0; background: #eef2f7; line-height: 1.55; font-size: 14px; }
  .page { max-width: 940px; margin: 24px auto; background: #fff; box-shadow: 0 10px 40px rgba(15,23,42,.12);
    border-radius: 14px; overflow: hidden; }
  .page-inner { padding: 0 40px 40px; }
  a { color: var(--brand); }

  /* Cover */
  .cover-band { background: linear-gradient(135deg, var(--brand) 0%, var(--brand2) 100%); color: #fff;
    padding: 28px 40px 32px; margin: 0 -40px; }
  .cover-head { display: flex; justify-content: space-between; align-items: center; opacity: .92; font-size: 12px; }
  .brand-mark { font-weight: 800; letter-spacing: .5px; }
  .cover-band h1 { font-size: 30px; margin: 16px 0 4px; font-weight: 800; line-height: 1.15; }
  .cover-sub { margin: 0; opacity: .85; font-size: 13px; }
  .cover-hero { display: flex; gap: 26px; align-items: center; margin-top: 22px; flex-wrap: wrap; }
  .gauge-wrap { flex: 0 0 auto; }
  .cover-facts { display: grid; grid-template-columns: 1fr 1fr; gap: 10px 24px; flex: 1; min-width: 240px; }
  .fact { display: flex; flex-direction: column; gap: 2px; }
  .fact span { font-size: 11px; text-transform: uppercase; letter-spacing: .6px; opacity: .8; }
  .fact b { font-size: 14px; font-weight: 600; }
  .fact em { opacity: .7; font-style: normal; }
  .risk-pill { display: inline-block; padding: 2px 12px; border-radius: 999px; background: rgba(255,255,255,.2);
    border: 1px solid rgba(255,255,255,.6); font-weight: 700; font-size: 13px; }
  .verdict-banner { margin: 18px 0 0; padding: 14px 18px; background: var(--soft); border: 1px solid var(--line);
    border-inline-start: 4px solid var(--brand); border-radius: 10px; font-size: 14px; }
  .v-tag { font-weight: 800; color: var(--brand); text-transform: uppercase; font-size: 11px; letter-spacing: .5px; margin-inline-end: 6px; }

  /* Sections */
  .sec { margin-top: 30px; break-inside: avoid; }
  .sec h2 { font-size: 17px; font-weight: 800; color: var(--ink); margin: 0 0 14px; display: flex; align-items: center; gap: 9px; }
  .sec-dot { width: 9px; height: 20px; border-radius: 3px; background: linear-gradient(var(--brand), var(--brand2)); display: inline-block; }
  h3 { font-size: 13px; font-weight: 700; margin: 18px 0 8px; color: #334155; }
  .lead { font-size: 14px; color: #334155; margin: 4px 0 0; }
  .muted { color: var(--muted); }

  /* KPI cards */
  .kpi-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }
  .kpi { background: var(--soft); border: 1px solid var(--line); border-radius: 12px; padding: 14px 16px; }
  .kpi-val { font-size: 24px; font-weight: 800; line-height: 1.1; }
  .kpi-label { font-size: 11px; text-transform: uppercase; letter-spacing: .5px; color: var(--muted); margin-top: 4px; }
  .kpi-sub { font-size: 12px; color: #475569; margin-top: 3px; }

  /* Bars */
  .charts-row { display: flex; gap: 26px; align-items: flex-start; flex-wrap: wrap; }
  .charts-bars { flex: 1; min-width: 300px; }
  .charts-radar { flex: 0 0 auto; text-align: center; }
  .bars { display: flex; flex-direction: column; gap: 9px; }
  .bar-row { font-size: 12.5px; }
  .bar-head { display: flex; justify-content: space-between; margin-bottom: 3px; }
  .bar-val { font-weight: 700; font-variant-numeric: tabular-nums; }
  .bar-track { height: 8px; background: #eef2f7; border-radius: 6px; overflow: hidden; }
  .bar-fill { height: 100%; border-radius: 6px; }

  .callout { margin: 16px 0 0; padding: 12px 15px; background: #eef2ff; border: 1px solid #dbe0ff;
    border-radius: 10px; font-size: 13px; color: #1e293b; }
  .callout.refactor { background: #ecfdf5; border-color: #bbf7d0; }

  /* Tables */
  table { width: 100%; border-collapse: collapse; margin: 8px 0 0; font-size: 13px; }
  th, td { border-bottom: 1px solid var(--line); padding: 8px 10px; text-align: ${dir === "rtl" ? "right" : "left"}; }
  thead th { background: var(--soft); font-weight: 700; font-size: 12px; color: #475569; border-bottom: 2px solid var(--line); }
  .mtable tbody tr:nth-child(even) { background: #fbfcfe; }
  .numc { text-align: ${dir === "rtl" ? "left" : "right"}; font-variant-numeric: tabular-nums; }
  .delta-up { color: #dc2626; font-weight: 700; }
  .delta-down { color: #059669; font-weight: 700; }
  .delta-zero { color: var(--muted); }

  /* Clone chips */
  .coverage { margin-bottom: 16px; }
  .coverage-head { display: flex; justify-content: space-between; font-size: 12.5px; margin-bottom: 5px; }
  .chips { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; }
  .chip { display: flex; align-items: center; gap: 8px; padding: 9px 12px; border-radius: 10px; font-size: 12.5px;
    border: 1px solid var(--line); background: #fff; }
  .chip-dot { width: 9px; height: 9px; border-radius: 50%; background: #cbd5e1; flex: 0 0 auto; }
  .chip.on { border-color: #fecaca; background: #fef2f2; font-weight: 600; }
  .chip.on .chip-dot { background: #dc2626; }
  .chip-state { margin-inline-start: auto; font-size: 11px; color: var(--muted); }
  .chip.on .chip-state { color: #dc2626; }

  /* Findings */
  .badge { display: inline-block; padding: 2px 9px; border-radius: 999px; font-size: 11px; font-weight: 700;
    text-transform: capitalize; color: var(--bc); border: 1px solid var(--bc); background: color-mix(in srgb, var(--bc) 10%, #fff); }
  .finding { border: 1px solid var(--line); border-inline-start: 4px solid var(--fc); border-radius: 10px;
    padding: 12px 15px; margin-top: 10px; break-inside: avoid; }
  .finding-head { display: flex; align-items: center; gap: 9px; margin-bottom: 5px; }
  .finding-head b { font-size: 13.5px; }
  .finding p { margin: 0; font-size: 13px; color: #334155; }

  /* Prose (AI narrative) */
  .prose { font-size: 13.5px; color: #1e293b; }
  .prose h1, .prose h2, .prose h3 { color: var(--ink); }
  .prose p { margin: 8px 0; }
  .prose pre, pre { background: #0f172a; color: #e2e8f0; border-radius: 8px; padding: 12px 14px; overflow-x: auto;
    white-space: pre-wrap; word-break: break-word; font-size: 12px; line-height: 1.5;
    font-family: "SF Mono", "Cascadia Code", Consolas, monospace; direction: ltr; text-align: left; }
  .analysis-text { background: var(--soft); color: var(--ink); border: 1px solid var(--line); }

  /* Quality + source */
  .quality-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
  .quality-card { border: 1px solid var(--line); border-radius: 10px; padding: 4px 14px 14px; background: #fff; break-inside: avoid; }
  pre.code { background: #0f172a; color: #e2e8f0; }

  .footer { margin-top: 34px; padding-top: 14px; border-top: 1px solid var(--line); display: flex;
    justify-content: space-between; font-size: 11px; color: var(--muted); }

  .print-btn { position: fixed; top: 16px; ${dir === "rtl" ? "left" : "right"}: 16px; z-index: 10;
    background: var(--brand); color: #fff; border: 0; padding: 10px 16px; border-radius: 8px; cursor: pointer;
    font-size: 13px; font-weight: 600; box-shadow: 0 6px 20px rgba(79,70,229,.4); }
  .print-btn:hover { background: #4338ca; }

  @media print {
    body { background: #fff; }
    .page { box-shadow: none; border-radius: 0; margin: 0; max-width: none; }
    .print-btn { display: none; }
    .sec, .finding, .quality-card, .kpi { break-inside: avoid; }
  }
  @media (max-width: 620px) {
    .kpi-grid, .quality-grid, .chips { grid-template-columns: 1fr; }
    .page-inner, .cover-band { padding-left: 20px; padding-right: 20px; }
    .cover-band { margin: 0 -20px; }
  }
  @page { size: A4; margin: 14mm; }
</style></head>
<body>
  <button class="print-btn" onclick="window.print()">${esc(L.print)}</button>
  <div class="page">
    <div class="page-inner">
      ${parts.join("\n")}
      <div class="footer"><span>${esc(L.footer)}</span><span>${esc(now)}</span></div>
    </div>
  </div>
</body></html>`;

  return doc;
}

export function openPdfReport(result: AnalysisResult, sections: PdfSections, lang: Lang): void {
  const doc = buildReportHtml(result, sections, lang);
  const win = window.open("", "_blank", "noopener,noreferrer");
  if (!win) {
    // Popup blocked — fall back to a downloadable HTML file.
    const blob = new Blob([doc], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `analysis-${result.saved_analysis_id ?? "report"}.html`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 0);
    return;
  }
  win.document.open();
  win.document.write(doc);
  win.document.close();
}
